env:
  global:
    - secure: "token"


dist: trusty
sudo: true
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cmake
            - conan
    coverity_scan:

        project:
            name: selassje/codility
            version: 1.0
            description: codility

        notification_email: przemkoz85@gmail.com

        build_command_prepend: cd rubidium2018/build/gnu

        build_command: bash build.sh  

        branch_pattern: coverity_scan
matrix:
    include:
        - language: python
          python: 3.6
          script:
           - python strontium2019/strontium.py
            
        - language: cpp
          compiler: gcc
          script:
            - cd rubidium2018/build/gnu
            - bash  build.sh
            - cd ../../bin
            - ./rubidium