dist: trusty
sudo: true
matrix:
    include:
        - language: python
        python: 3.7
        script:
            - python strontium2019/strontium.py
            
        - language: cpp
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - gcc-6
                    - g++-6
                    - cmake
        script:
            - export CC=/usr/bin/gcc-6
            - export CXX=/usr/bin/g++-6
            - gcc -v && g++ -v && cmake --version
            - cd rubidium2018
            - mkdir build && cd build
            - cmake ..
            - make
            - ../bin/rubidium