dist: trusty
sudo: true
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cmake
matrix:
    include:
        - language: python
          python: 3.6
          script:
           - python strontium2019/strontium.py
            
        - language: cpp
          compiler: gcc
          script:
            - gcc -v && g++ -v && cmake --version
            - cd rubidium2018/build/gnu
            - cmake ../..
            - make
            - ../../bin/rubidium